"""模块 10：受控、可追溯 RAG 合同工作台。"""

from .answer_evaluation import (
    AnswerEvaluationCase,
    AnswerEvaluationFixtureError,
    AnswerEvaluationReport,
    AnswerEvaluationResult,
    evaluate_answer_case,
    load_answer_cases,
    run_answer_evaluation,
    write_public_answer_report,
)
from .answering import (
    AnswerContractError,
    AnswerStatus,
    Citation,
    GroundedAnswer,
    SourceBoundAnswerClient,
    StructuredAnswerTransport,
)
from .core import (
    Chunk,
    ChunkingError,
    CourseDocument,
    DocumentError,
    EmbeddingProvider,
    HashingEmbeddingProvider,
    IndexErrorContract,
    InMemoryVectorIndex,
    QueryError,
    RetrievalResult,
    RetrievedChunk,
    chunk_document,
)
from .evaluation import (
    EvaluationFixtureError,
    RetrievalEvaluationCase,
    RetrievalEvaluationReport,
    RetrievalEvaluationResult,
    evaluate_case,
    run_retrieval_evaluation,
    write_public_report,
)
from .openai_answer_transport import (
    AnswerTransportRejectedError,
    AnswerTransportUnavailableError,
    OpenAiSourceBoundAnswerTransport,
)

__all__ = [
    "AnswerContractError",
    "AnswerEvaluationCase",
    "AnswerEvaluationFixtureError",
    "AnswerEvaluationReport",
    "AnswerEvaluationResult",
    "AnswerStatus",
    "AnswerTransportRejectedError",
    "AnswerTransportUnavailableError",
    "Chunk",
    "ChunkingError",
    "Citation",
    "CourseDocument",
    "DocumentError",
    "EmbeddingProvider",
    "EvaluationFixtureError",
    "GroundedAnswer",
    "HashingEmbeddingProvider",
    "IndexErrorContract",
    "OpenAiSourceBoundAnswerTransport",
    "InMemoryVectorIndex",
    "QueryError",
    "RetrievedChunk",
    "RetrievalEvaluationCase",
    "RetrievalEvaluationReport",
    "RetrievalEvaluationResult",
    "RetrievalResult",
    "SourceBoundAnswerClient",
    "StructuredAnswerTransport",
    "chunk_document",
    "evaluate_answer_case",
    "evaluate_case",
    "load_answer_cases",
    "run_answer_evaluation",
    "run_retrieval_evaluation",
    "write_public_answer_report",
    "write_public_report",
]
